blog/urls.py
#-*- coding: utf-8 -*-
"""blogproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from . import views

app_name = 'blog' #告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
urlpatterns = [
    #url(r'^$', views.index, name='index'),
    #as_view()将类视图转换成函数视图
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='urltag'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^about', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),

    #两个括号括起来的地方是两个命名组参数，Django 会从用户访问的 URL 中自动提取这两个参数的值，然后传递给其对应的视图函数。
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^author/(?P<pk>[0-9]+)/$', views.author, name='author'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),

    url(r'', include('django.contrib.auth.urls')),
    url(r'', include('users.urls')),
]

comments/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-

from django.conf.urls import url
from . import views
app_name = 'comments'
urlpatterns = [
        url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

users/urls.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-

from django.conf.urls import url, include
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    #url(r'^$', include('django.contrib.auth.urls'), name='login'),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Category(models.Model):
    #博客分类的名称
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Tag(models.Model):
    #标签名
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Post(models.Model):
    #文章表

    #标题
    title = models.CharField(max_length=70)

    #正文
    body = models.TextField()

    #创建时间和最后修改时间
    create_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    #文章摘要 blank=True 允许空值存入
    excerpyt = models.CharField(max_length=200, blank=True)

    #规定一篇文章只能有一个分类,但是一个分类下可以有多篇文章,所以使用ForeignKey,一对多关联关系
    #对于标签而言,一篇文章可以后多个标签,同一个标签下面也可以有多篇文章,所以使用多对多关联关系,ManyToManyField
    #同时规定文章可以没有标签,一次tags指定:blank=True.

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    #文章作者,这里User是从django.contrib.auth.models 导入的
    #django.contrib.auth 是Django内置的应用,专门用来处理网站用户的注册和登陆等流程,User是Django内置的用户模型
    #此处通过ForeignKey把文章和User关联了起来.
    #一个文章只能有一个作者,一个作者会有多篇文章,因此是一对多
    author = models.ForeignKey('users.User')

    #新增views字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    #'blog:detail'，意思是 blog 应用下的 name=detail 的函数
    #于是 reverse 函数会去解析这个视图函数对应的 URL，我们这里 detail 对应的规则就是 post/(?P<pk>[0-9]+)/ 这个正则表达式，
    # 而正则表达式部分会被后面传入的参数 pk 替换
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    #定义Meta内部类,通过指定一些属性来规定这个类该有的一些特性
    #此处指定排序方式
    class Meta:
        ordering = ['-create_time'] #依据create_time属性值进行排序

comments/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Comment(models.Model):
    #一个用户有多条评论,一条评论只能有一个人
    name = models.ForeignKey('users.User')

    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True) # 当评论数据保存到数据库时，自动把 created_time 的值指定为当前时间

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return  self.text[:20]

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
import markdown
from comments.forms import CommentForm

from django.views.generic import ListView
from django.db.models import Q

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        '''
        在视图函数中将模板变量通过render函数的context参数传给一个字典,
        在类视图中,这个模板字典通过get_context_data获得,所以要复写该方法,插入一些自定义模板变量
        '''

        #首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        #父类字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        #paginator 是 Paginator 的一个实例， page_obj 是 Page 的一个实例， is_paginated 是一个布尔变量，用于指示是否已分页。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)

        #分页导航条的模板变量更新到 context 中，pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        #context更新后返回,便于ListView根据context渲染模板
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            #当没有足够的数据条数分页时 不需要分页
            return {}

        #当前页的左右页码号
        left = []
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False
        right_has_more = False

        #当 当前页的左边已经可以显示出1页时,则不必重复显示第1页
        first = False
        last = False

        #当前页码
        page_number = page.number

        #分页后的总页数
        total_pages = paginator.num_pages
        #print(total_pages)

        #整个分页的页码表,如果分了四页则应该是:[1, 2, 3, 4]
        page_range = paginator.page_range
        #print(page_range)

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            #最右边的页不是最后一页  需要显示省略号
            if right[-1] < total_pages -1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] <total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据
            left = page_range[(page_number - 3) if (page_number -3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        else:
            left = page_range[(page_number - 3) if (page_number -3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages -1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data

class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    #复写了父类的 get_queryset 方法
    def get_queryset(self):
        #在类视图中,从URL捕获的命名组参数值都保存在实例的kwargs属性的字典里
        #非命名组参数值保存在实例的args属性列表里
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

def search(request):
    q = request.GET.get('sq') #获取get提交的参数
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/results.html', {'error_msg':error_msg})

    #icontains 是查询表达式（Field lookups）  i是指不去分大小写,用法就是在需要筛选的模型后面加两个下划线
    #Q 对象用于包装查询表达式
    post_list = Post.objects.filter(Q(title__icontains = q) | Q(body__icontains =q))
    return render(request, 'blog/results.html', {'error_msg': error_msg,
                                                 'post_list': post_list})

def index(request):
    #order_by 方法对这个返回的 queryset 进行排序。排序依据的字段是 created_time，即文章的创建时间。- 号表示逆序
    #post_list = Post.objects.all().order_by('-create_time')
    post_list = Post.objects.all() #添加Meta后删除orderby
    return render(request, 'blog/index.html', context={'post_list':post_list})

def detail(request, pk):
    post = get_object_or_404(Post, pk = pk) #根据models中reverse函数返回的pk键值查找对应的内容

    #方法很笨,没访问一次+1  已有再优化
    post.increase_views()

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm() #Django 自动创建的html  表单
    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all().order_by('-created_time')
    context = {'post': post,
               'form': form, #包含了自动生成 HTML 表单的全部数据
               'comment_list': comment_list
               }
    return render(request, 'blog/detail.html', context=context)

#归档页面  归档的下的文章列表的显示和首页是一样的，因此我们直接渲染了index.html 模板
def archives(request, year, month):
    post_list = Post.objects.filter(create_time__year=year,
                                    create_time__month=month
                                    )            #.order_by('-create_time')
    return render(request, 'blog/index.html', context={'post_list':post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk) #根据主键值取得分类的名字
    post_list = Post.objects.filter(category=cate)    #.order_by('-create_time')
    return render(request, 'blog/index.html', context={'post_list':post_list})

def about(request):
    return render(request, 'about.html')

def author(request, pk):
    auth = get_object_or_404(Post, pk=pk)
    post_list = Post.objects.filter(author=auth.author)  #匹配出所有该作者的文章
    return render(request, 'blog/index.html', context={'post_list':post_list})

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block main %}
<article class="post post-{{ post.pk }}" xmlns="http://www.w3.org/1999/html">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{%url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
            <span class="post-author"><a href="{% url 'blog:author' post.pk %}">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            {% for tag in post.tags.all %}
            <span class="post-tag"><a href="{% url 'blog:urltag' tag.pk %}"> 标签:{{tag.name}}</a></span>
            {% endfor %}
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}
    </div>
</article>
<section class="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <!--
                {{ form.name }}
                -->
                <input type="hidden" name="name"  id="id_name" value="{{ user.username }}">
            </div>
            <!--
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">URL：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            -->
            <div class="col-md-12">
                {% if user.is_authenticated %}
                    <label for="{{ form.text.id_for_label }}">{{ user.username }} 评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                {% else %}
                <div style="border-style: ridge">

                    <br/>
                     您需要登录后才可以评论 :
                     <a href="{% url 'login' %}?next={{ request.path }}" data-hover="登陆">登陆</a>
                     <input type="hidden" name="next" value="{{ next }}">
                     &nbsp;|&nbsp;
                     <a href="{% url 'users:register' %}?next={{ request.path }}' %}" data-hover="注册">注册</a>
                    <input type="hidden" name="next" value="{{ next }}">
                </div>
                {% endif %}
            </div>
        </div> <!-- row done -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{post.comment_set.count}}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date"
                      datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            </li>
            {% empty %}
            暂无评论
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}
{% block toc %}

{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
    <title>HangLinux</title>
{% endblock %}

{%block main %}
{% for post in post_list %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}" target="_blank">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{%url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
            <span class="post-author"><a href="{% url 'blog:author' post.pk %}">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <!-- 文章摘要字段 方法1
        <p>{{ post.excerpt }}</p>
        -->
        <!-- 模板过滤器方式-->
        <p>{{ post.body | truncatechars:35}}</p>

        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" target="_blank" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty%}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}

<!-- 简单分页效果
<div class="pagination-simple">
    <a href="#">上一页</a>
    <span class="current">第 6 页 / 共 11 页</span>
    <a href="#">下一页</a>
</div>
-->
    {% if is_paginated %}
        <div class="pagination">
            <ul>
                {% if first %}
                    <li><a class="page" href="?page=1">1</a></li>
                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                    {% for i in left %}
                        <li><a class="page" href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                <li><a class="current page current" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                {% if right %}
                    {% for i in right %}
                        <li><a class="page" href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    {% if right_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                {% endif %}
                {% if last %}
                    <li><a href="?page={{ paginator.num_pages }}" class="page">{{ paginator.num_pages }}</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock main %}

templates/blog/results.html
{% extends 'base.html' %}

{%block main %}

{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

{% for post in post_list %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}" target="_blank">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="#">588 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" target="_blank" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">
    没有搜索到符合条件的文章
</div>
{% endfor %}

{% endblock main %}