blog/urls.py
#-*- coding: utf-8 -*-
"""blogproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from . import views

app_name = 'blog' #告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
urlpatterns = [
    #url(r'^$', views.index, name='index'),
    #as_view()将类视图转换成函数视图
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='urltag'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^about', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),

    #两个括号括起来的地方是两个命名组参数，Django 会从用户访问的 URL 中自动提取这两个参数的值，然后传递给其对应的视图函数。
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^author/(?P<pk>[0-9]+)/$', views.author, name='author'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),

    url(r'', include('django.contrib.auth.urls')),
    url(r'', include('users.urls')),
]

users/urls.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-

from django.conf.urls import url, include
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    #url(r'^$', include('django.contrib.auth.urls'), name='login'),
]

templates/about.html
{% extends 'base.html' %}
{% block main %}


<div class="content-body">
    <article class="aboutcon">
        <h1 class="t_nav"><span>谁拿流年乱了浮生,又借浮生乱了红尘.此生若能得幸福安稳,谁又愿颠沛流离?</span><a href="/" class="n1">网站首页</a><a href="/about.html" class="n2">关于我</a></h1>
        <div class="about left">
            <h2>About me</h2>
            <ul>
                <p>2014年大学毕业后一直从事Linux平台下开发工作.热爱技术,坚信键盘创造美好未来.</p>
                <p>
                  一直在路上,学习 实践 提高.
                </p>
                <h4>
                  个人简短小结:
                </h4>
                <p>
                    Linux: 2012年开始接触linux,和所有刚接触linux的同学一样,几乎玩遍了所有发行版本,只为找一款适合自己的.最后选中了沉稳的CentOS学习服务器搭建和基本基本操作技能;在后来开发过程中,越来越发现CentOS在解决库依赖和安装小众软件过程中的"不友好",别人家的"apt-get install",而我要折腾一晚上...</br>遂慢慢转向apt阵营,在个人日常PC上还是使用Debian比较方便! 当然,在部署服务器的时候我还是会选择CentOS,部署方便的资料较多,可以少走很多弯路,而且到了CentOS7在用户友好方面真的提升了不少.</p>

                </p>
                <p>
                   Code:最早接触的是C,工作中大部分时间也是用C.还是比较喜欢C语言解决问题的简单直接高效.当然在系统部署和系统控制等地方shell脚本不仅仅是解脱你的双手,更重要的是节约了大把时间. 在2015年工作中接触到了Python,被它的简单易用丰富的安装包所折服,印证了"人生苦短,我用Python".
                </p>
                <p>
                    一点感想:万丈高楼平地起,社会很浮躁,但是内心要宁静.这真的是最好的时代,每个人通过自己的努都能过上好日子.虽然技术更新迭代很快,但是在变种总有不变.不变的就是计算机科学原理.所以还是要沉下来,学习,提高,更好的服务社会.
                </p>
            </ul>
            <h2>About my blog</h2>
            <p>博客框架刚搭建好,还有很多地方待优化,以前的博文会陆续迁移过来...</p>
            <p>本博客架构:the web client <-> the web server(nginx) <-> the socket <-> uWSGI <-> Python(Django)</p>


        </div>
        <aside class="right">
            <div class="about_c">
                <p>CSDN博客:<a href="http://blog.csdn.net/hanglinux" target="_blank"> hanglinux</a></p>
                <p>github:<a href="https://github.com/hakits" target="_blank"> hakits</a></p>
                <p>籍贯：山东省临沂市</p>
                <p>现居：深圳市宝安西乡</p>
                <p>喜欢的电影：《霍元甲》(2016，李连杰)  《钢铁侠》 《复仇者联盟》</p>
                <p>联系方式：hanglinux@163.com</p>

            </div>
        </aside>
    </article>
</div>

{% endblock main %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    {% block title %}
    <title>Hakit Linux</title>
    {% endblock %}
    <link rel="shortcut icon" href="/static/image/favicon.ico" />

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">
    <link rel="stylesheet" href="/static/css/highlights/github.css">
    <link rel="stylesheet" href="/static/css/about.css">

    <!-- js -->
    <script src="http://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="http://cdn.bootcss.com/pace/0.5.6/pace.min.js"></script>
    <script src="http://cdn.bootcss.com/modernizr/2.7.1/modernizr.min.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index'%}"><b>Hakit</b> &amp; Linux</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li id="headtitle" class="cl-effect-11"><a href="{%url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li id="headtitle" class="cl-effect-11"><a href="{%url 'blog:about' %}" data-hover="关于">关于</a></li>
                            {% if user.is_authenticated %}
                                <li id="login" class="cl-effect-11"><a href="{%url 'blog:about' %}" data-hover="{{ user.username }}">{{ user.username }}</a></li>
                                <li id="login" class="cl-effect-11"><a href="{% url 'password_change' %}?next={{ request.path }}" data-hover="修改密码">修改密码</a></li>
                                <li id="login" class="cl-effect-11"><a href="{% url 'logout' %}?next={{ request.path }}" data-hover="注销">注销</a></li>
                            {% else %}
                                <li id="login" class="cl-effect-11"><a href="{% url 'login' %}?next={{ request.path }}" data-hover="登陆">登陆</a></li>
                                <li id="login" class="cl-effect-11"><a href="{% url 'users:register' %}?next={{ request.path }}" data-hover="注册">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" placeholder="搜索" required name="sq">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://hakits.tech/">hakit的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章!
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档!
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts}})</span></a>
                        </li>
                        {% empty %}
                        暂无分类!
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:urltag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签!
                    </ul>
                    {% endfor %}
                </div>
            </aside>
        </div>
    </div>
</div>


<button onclick="topFunction()" id="myBtn" title="回顶部">返回顶部</button>
<script>
// 当网页向下滑动 20px 出现"返回顶部" 按钮
window.onscroll = function() {scrollFunction()};

function scrollFunction() {console.log(121);
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// 点击按钮，返回顶部
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script


        <!--当页面为about页面时 隐藏右边侧栏-->
<script type="text/javascript">
	(function() {
       var query = window.location.pathname;
       //console.log(query);
       if (query == '/about' || query == '/about.html' || query == '/about/')
       {
       	//	console.log("I Cache you!")
			$(".widget").hide();
       }
	})();
</script>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://hakits.tech/" title="网页模板">hakit</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="about.html">关于</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>

<!--蜘蛛网背景效果--->
<script type="text/javascript" color="5,39,175" opacity="0.5" src="http://cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js"></script>
<!-- 页面点击小红心 -->
<script type="text/javascript" src="/static/js/love.js"></script>
<!--可变丝带-->
<script type="text/javascript" alpha="0.2" src="http://cdn.atool.org/res/ribbon.min.js"></script>

</body>
</html>

templates/loginbase.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    {% block title %}
    {% endblock %}
    <link rel="shortcut icon" href="/static/image/favicon.ico" />
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'blog:index' %}">Hakit's blog</a></h1>
                {% block userbody %}
                {% endblock%}
            </div>
        </div>
    </div>
</div>

<!--蜘蛛网背景效果--->
<script type="text/javascript" color="5,39,175" opacity="0.5" src="/static/js/canvas-nest.min.js"></script>
<!-- 页面点击小红心 -->
<script type="text/javascript" src="/static/js/love.js"></script>
<!--可变丝带-->
<script type="text/javascript" alpha="0.2" src="http://cdn.atool.org/res/ribbon.min.js"></script>

</body>
</html>